trigger:
- main  # Adjust if the default branch is different

pool:
  name: 'Default'  # Use the default agent pool for self-hosted agents (if not created a custom pool)
  demands:
    - agent.name -equals 'vstsagent.Kavindhiran1735638777857.Default.KAVIN'  # Correct demand syntax to match agent name

steps:
- task: UseNode@1
  inputs:
    versionSpec: '16.x'  # Adjust Node.js version if required
    addToPath: true

- script: |
    npm install  # Install dependencies from package.json
  displayName: 'Install dependencies'

- script: |
    npm run build  # Run the build script (adjust if different in the repo)
  displayName: 'Build the website'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'  # Path for build output
    ArtifactName: 'html-website'  # You can change this name
    publishLocation: 'Container'
